const content = [
    "Never trust a dog to watch your food.",
    "When your dad is mad and asks you 'Do I look stupid?', don't answer.",
    "Never tell your mom her diet's not working.",
    "Never pee on an electric fence.",
    "Don't pull Dad's finger when he tells you to.",
    "When your mom is mad at your dad, don't let her brush your hair.",
    "Never let your three-year old brother in the same room as your school assignment.",
    "Don't sneeze in front of mom when you're eating crackers.",
    "A puppy always has bad breath - even after eating a Tic-Tac.",
    "You can't hide a piece of broccoli in a glass of milk.",
    "Don't wear polka-dot underwear under white shorts.",
    "If you want a kitten, start out by asking for a horse.",
    "Felt-tip markers are not good to use as lipstick.",
    "Don't pick on your sister when she's holding a baseball bat.",
    "When you get a bad grade in school, show it to your mom when she's on the phone.",
    "If the shoe fits, buy it every color.",
    "When at first you don't succeed, just eat cake. Then try again.",
    "Raisin cookies looking like chocolate chip cookies is why I have trust issues.",
    "Life is short, so eat dessert first.",
    "If I had 100 friends, I would turn the phone off.",
    "Unless there is someone there to catch you, the rules are only guidelines.",
    "For $1, you can buy a candy bar from a vending machine. For $2, you can buy a brick, and get all the candy in the vending machine.",
    "Don't give up on your dreams. Keep on sleeping.",
    "Be a smart feller, not a fart smeller.",
    "Treat every problem as your dog would. If you can't eat it, walk away.",
    "Don't sweat the petty things and don't pet the sweaty things.",
    "The one who cries the hardest wins the argument.",
    "Never test the depth of a river with both feet.",
    "The early bird may catch the worm, but the second mouse gets the cheese.",
    "If life gives you lemons, squeeze the juice into a water gun and shoot other people in the eyes. :)",
    "When you want something expensive, ask your grandparents.",
    "Never ask for anything that costs more than five dollars when your parents are doing taxes.",
    "Sometimes the road less traveled is the road less traveled for a reason.",
    "Don't make decisions when you are angry, and don't make promises when you are happy.",
    "If you want to hold a family meeting, turn off the Wi-Fi and wait near the router.",
    "If you're going to break the rules, only break one rule at a time.",
    "Always let people underestimate you. That way, its easier to beat them.",
    "When you're with new friends, don't talk about old friends.",
    "If the grass is greener on the other side, there's probably more manure there.",
];

export default content;